Добавил гайд по настройке Банжикорда
superhub-host/wiki pull request #35
Opened 2023-01-24 15:27 UTC by PystoyPlayer

Проверьте форматирование текста

2023-01-24 15:35 UTC, PerchunPak requested changes

2023-01-24 15:35 UTC, PerchunPak commented on pages/guides/configure-proxy
> +---
Может перевести изображение?

2023-01-24 15:35 UTC, PerchunPak commented on pages/guides/configure-proxy
> +![Proxy!](/images/configure-proxy/proxy.png "Proxy")
Вот тут что то нечистое с синтаксисом, но ладно.

2023-01-24 15:35 UTC, PerchunPak commented on pages/guides/configure-proxy
> +Первым делом необходимо купить отдельный сервер Java Edition Proxy **[(страница покупки)](https://superhub.host/order/minecraft)**. Можно выбрать любой форк BungeeCord'а, но я бы рекомендовал FlameCo
Зачем выделять ссылки жирным?

2023-01-24 15:35 UTC, PerchunPak commented on pages/guides/configure-proxy
> +  1. Если ваш сервер пиратский, найдите строку `online_mode` и замените true на false. Тогда проверка лицензии будет отключена.
True и false лучше поместить в `

2023-01-24 15:35 UTC, PerchunPak commented on pages/guides/configure-proxy
> +  2. Ищем параметр: `host: 0.0.0.0:25577` и заменяем порт 25577 на порт своего прокси сервера.
Это должна делать панель, но нужно проверить

2023-01-24 15:35 UTC, PerchunPak commented on pages/guides/configure-proxy
> +      ```servers:
```suggestion
      ```yaml
      servers:
```

2023-01-24 15:35 UTC, PerchunPak commented on pages/guides/configure-proxy
> +          motd: '&1Выживание'
Насколько я помню, эта строка нигде не отображается. Нужно проверить.

2023-01-24 15:35 UTC, PerchunPak commented on pages/guides/configure-proxy
> +          restricted: false```
```suggestion
          restricted: false
\```
```
(Без \\)

2023-01-24 15:35 UTC, PerchunPak commented on pages/guides/configure-proxy
> +  5. В завершении находим параметр `ip_forward: false` и меняем его значение на true. Далее на всех игровых серверах, подключаемых к прокси, открываем spigot.yml и меняем значение параметра bungeecor
Там в конце текста дублируется несколько раз

2023-01-24 15:35 UTC, PerchunPak commented on pages/guides/configure-proxy
> +    Эти манипуляции позволят защитить сервера от внешнего подключения и просто обязательно при настройке BungeeCord.
```suggestion
    Эти манипуляции позволят защитить сервера от внешнего подключения и просто обязательны при настройке BungeeCord.
```

2023-01-24 15:35 UTC, PerchunPak commented on pages/guides/configure-proxy
> +---
Нужно добавить ссылку на BungeeGuard

2023-01-24 15:45 UTC, PystoyPlayer commented on pages/guides/configure-proxy
> +![Proxy!](/images/configure-proxy/proxy.png "Proxy")
брал отсюда https://www.markdownguide.org/basic-syntax/#images-1

2023-01-24 15:45 UTC, PystoyPlayer commented on pages/guides/configure-proxy
> +Первым делом необходимо купить отдельный сервер Java Edition Proxy **[(страница покупки)](https://superhub.host/order/minecraft)**. Можно выбрать любой форк BungeeCord'а, но я бы рекомендовал FlameCo
а почему нет ?) Ну можно и не выделять

2023-01-24 15:46 UTC, PystoyPlayer commented on pages/guides/configure-proxy
> +  2. Ищем параметр: `host: 0.0.0.0:25577` и заменяем порт 25577 на порт своего прокси сервера.
Нет, я проверял

2023-01-24 15:47 UTC, PystoyPlayer commented on pages/guides/configure-proxy
> +          motd: '&1Выживание'
Отображается, если стоит ping passthrough или че то такое. Да и просто для себя хотя бы.

2023-01-24 15:52 UTC, PystoyPlayer commented on pages/guides/configure-proxy
> +---
а куда делать ссылка на твой гитхаб с FlameCord ?

2023-01-24 15:52 UTC, PystoyPlayer commented on pages/guides/configure-proxy
> +---
ну давай переведу

2023-01-24 16:06 UTC, PystoyPlayer commented on pages/guides/configure-proxy
> +  5. В завершении находим параметр `ip_forward: false` и меняем его значение на true. Далее на всех игровых серверах, подключаемых к прокси, открываем spigot.yml и меняем значение параметра bungeecor
? 
Скобка просто как должно быть чтобы видно было

2023-01-24 16:07 UTC, PerchunPak requested changes

2023-01-24 16:07 UTC, PerchunPak commented on pages/guides/configure-proxy
> +      - lobby```
```suggestion
      ```yaml
priorities:
  - lobby```
```

2023-01-24 16:07 UTC, PerchunPak commented on pages/guides/configure-proxy
> +          restricted: false
```suggestion
servers:
  lobby:
    motd: 'Лобби'
    address: 94.26.248.95:25567
    restricted: false
  survival:
    motd: '&1Выживание'
    address: 91.206.15.18:25568
    restricted: false
  minigames:
    motd: '&cСервер миниигр'
    address: 91.206.15.18:25569
    restricted: false
```

2023-01-24 16:12 UTC, PerchunPak commented on pages/guides/configure-proxy
> +Первым делом необходимо купить отдельный сервер Java Edition Proxy **[(страница покупки)](https://superhub.host/order/minecraft)**. Можно выбрать любой форк BungeeCord'а, но я бы рекомендовал FlameCo
> а куда делать ссылка на твой гитхаб с FlameCord ?

Ее лучше не публиковать, потому что она не долговечная и это не сильно понравиться автору. Можно оставить ссылку на https://builtbybit.com/resources/flamecord-mitigate-bots-exploits.13492/ и/или https://github.com/2lstudios-mc/FlameCord, но если хотят бесплатно - пусть выберут его как ядро при покупке. То что можно получить его написав нам лучше не упоминать.

2023-01-24 16:13 UTC, PerchunPak commented on pages/guides/configure-proxy
> +---
> а куда делать ссылка на твой гитхаб с FlameCord ?

лучше держать одну conversation для одной темы. [ответил тут](https://github.com/superhub-host/wiki/pull/35/files#r1085557317)

2023-01-25 18:11 UTC, PystoyPlayer commented on pages/guides/configure-proxy
> +Первым делом необходимо купить отдельный сервер Java Edition Proxy **[(страница покупки)](https://superhub.host/order/minecraft)**. Можно выбрать любой форк BungeeCord'а, но я бы рекомендовал FlameCo
Если выбрать при оформлении сервера, ядро не появится вроде

2023-01-25 19:17 UTC, PerchunPak commented on pages/guides/configure-proxy.md
> +    Настройке TCPShield **[(инструкция)](https://superhub.host/guides/configure-tcpshield)** или поэкспериментируйте с настройками прокси. Например, в modules.yml включение пункта `reconnect:` застав
```suggestion
## Возможные проблемы

1. `FlameCord: Country is blocked.` (Страна заблокирована)

    По умолчанию у FlameCord включен чёрный список стран для подключения к
    серверу, поэтому у вас может не получиться зайти. Для отключения фильтра
    заходим в `flamecord.yml` и находим блок ниже. Ставим `enabled: false`:

      ```yaml
      antibot:
        country:
          enabled: true
      ```

2. Максимально возможное число игроков для входа = 1. Помимо игрового сервера
это нужно изменить в config.yml на прокси в строке `max_players: 1`.

3. Сервер атакуют боты!

    Настройке TCPShield [(инструкция)](https://superhub.host/guides/configure-tcpshield)
    или поэкспериментируйте с настройками прокси. Например, в `modules.yml`
    включение пункта `reconnect:` заставит игрока переподключиться при первом
    заходе, чтобы доказать, что он человек.

4. Кто-то подключаеться на основной сервер в обход BungeeCord

    Обязательно, для всех Bungee сетей, необходимо настроить
    [BungeeGuard](https://superhub.host/guides/configure-tcpshield).
    Инструкцию можете найти по ссылке (на английском, если даже с
    переводчиком не понимаете - напишите нам в тех поддержку, поможем).
```

2023-01-25 19:57 UTC, ruscalworld commented on pages/guides/configure-proxy.md
> +BungeeCord — это прокси ядро для сервера Майнкрафт. Простыми словами, BungeeCord является шлюзом между вашими серверами.
> Простыми словами, BungeeCord является шлюзом между вашими серверами.

"Простыми словами" - как-то громко сказано. Ну я не понял по крайней мере)

Возможно, стоит подумать над тем, как заменить или подробнее раскрыть, поскольку человеку, который впервые столкнётся с настройкой банжи, вряд ли будет понятна такая формулировка.

2023-01-25 19:57 UTC, ruscalworld commented on pages/guides/configure-proxy.md
> +Первым делом необходимо [купить](https://superhub.host/order/minecraft) отдельный сервер Java Edition Proxy. Можно выбрать любой форк BungeeCord'а, но мы рекомендуем FlameCord.
> мы рекомендуем FlameCord

Возможно, стоит описать, почему именно его.

2023-01-25 21:03 UTC, PerchunPak requested changes

2023-01-25 21:03 UTC, PerchunPak commented on pages/guides/configure-proxy.md
> +```
Я специально оставил пробелы, потому что так оно красивее выходит.
![image](https://user-images.githubusercontent.com/68118654/214689647-658a4582-2a64-41cf-b52b-4ffbd5beb069.png)
![image](https://user-images.githubusercontent.com/68118654/214689622-4ee0e4ea-700a-4240-a98c-4fd8aab608e5.png)

2023-01-25 21:03 UTC, PerchunPak commented on pages/guides/configure-proxy.md
> +3. Сервер атакуют боты! [Настройте TCPShield](https://superhub.host/guides/configure-tcpshield) или поэкспериментируйте с настройками прокси. Например, в `modules.yml` включение пункта `reconnect:` з
нужно добавить ссылку на BungeeGuard

2023-01-25 21:03 UTC, PerchunPak commented on pages/guides/configure-proxy.md
> +BungeeCord — это прокси ядро для сервера Майнкрафт. Простыми словами, BungeeCord является шлюзом между вашими серверами.
https://sharegpt.com/c/3AVlB8I

2023-01-25 21:04 UTC, PystoyPlayer commented on pages/guides/configure-proxy.md
> +3. Сервер атакуют боты! [Настройте TCPShield](https://superhub.host/guides/configure-tcpshield) или поэкспериментируйте с настройками прокси. Например, в `modules.yml` включение пункта `reconnect:` з
бля куда она делась

2023-01-25 21:06 UTC, PystoyPlayer commented on pages/guides/configure-proxy.md
> +```
вроде на это гитхаб и жаловался, ну давай проверим

2023-01-25 21:06 UTC, PerchunPak commented on pages/guides/configure-proxy.md
> +Первым делом необходимо [купить](https://superhub.host/order/minecraft) отдельный сервер Java Edition Proxy. Можно выбрать любой форк BungeeCord'а, но мы рекомендуем FlameCord.
к сожалению, chatgpt не знает что такое flamecord((

![image](https://user-images.githubusercontent.com/68118654/214690608-288cdf63-5205-4384-9529-3d10cbbff560.png)

2023-01-25 21:14 UTC, PystoyPlayer commented on pages/guides/configure-proxy.md
> +```
вроде всё ок

2023-01-26 19:50 UTC, merged